services:
  flask_cv:
    build: docker_app/.
    ports:
      - "8001:8000"
  nginx:
    build: docker_server/.
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_cv
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw